package trainedge.htmleditor;

import java.util.ArrayList;
import java.util.HashMap;

/**
 * Created by Abc on 06-01-2017.
 */

public class TabDataList {

    private static ArrayList<String> tabList;
    private static ArrayList<String> tabData;

    public static ArrayList<String> getTabs(){
        tabList = new ArrayList<>();
        tabList.add("html");
        tabList.add("head");
        tabList.add("title");
        tabList.add("body");
        tabList.add("style");
        tabList.add("script");
        tabList.add("base");
        tabList.add("meta");
        tabList.add("link");
        tabList.add("a");
        tabList.add("img");
        tabList.add("h1");
        tabList.add("h2");
        tabList.add("h3");
        tabList.add("h4");
        tabList.add("h5");
        tabList.add("h6");
        tabList.add("div");
        tabList.add("p");
        tabList.add("span");
        tabList.add("br");
        tabList.add("hr");
        tabList.add("ol");
        tabList.add("ul");
        tabList.add("li");
        tabList.add("dl");
        tabList.add("dt");
        tabList.add("dd");
        tabList.add("map");
        tabList.add("area");
        tabList.add("strong");
        tabList.add("b");
        tabList.add("em");
        tabList.add("i");
        tabList.add("cite");
        tabList.add("pre");
        tabList.add("q");
        tabList.add("abbr");
        tabList.add("acronym");
        tabList.add("address");
        tabList.add("dfn");
        tabList.add("code");
        tabList.add("font");
        tabList.add("sub");
        tabList.add("sup");
        tabList.add("del");
        tabList.add("ins");
        tabList.add("blockquote");
        tabList.add("small");
        tabList.add("bdo");
        tabList.add("charset");
        tabList.add("target");
        tabList.add("rel");
        tabList.add("href");
        tabList.add("id");
        tabList.add("src");
        tabList.add("alt");
        tabList.add("align");
        tabList.add("border");
        tabList.add("vspace");
        tabList.add("hspace");
        tabList.add("height");
        tabList.add("width");
        tabList.add("name");
        tabList.add("type");
        tabList.add("form");
        tabList.add("fieldset");
        tabList.add("legend");
        tabList.add("input");
        tabList.add("label");
        tabList.add("action");
        tabList.add("method");
        tabList.add("enctype");
        tabList.add("autocomplete");
        tabList.add("novalidate");
        tabList.add("accept_charsets");
        tabList.add("target");
        tabList.add("value");
        tabList.add("size");
        tabList.add("maxlength");
        tabList.add("required");
        tabList.add("step");
        tabList.add("placeholder");
        tabList.add("pattern");
        tabList.add("min");
        tabList.add("max");
        tabList.add("autofocus");
        tabList.add("disabled");
        tabList.add("textarea");
        tabList.add("select");
        tabList.add("multiple");
        tabList.add("optgroup");
        tabList.add("option");
        tabList.add("selected");
        tabList.add("button");
        tabList.add("table");
        tabList.add("caption");
        tabList.add("thead");
        tabList.add("tbody");
        tabList.add("tfoot");
        tabList.add("tr");
        tabList.add("th");
        tabList.add("td");
        tabList.add("colgroup");
        tabList.add("col");
        tabList.add("object");
        tabList.add("iframe");
        tabList.add("param");
        tabList.add("embed");
        tabList.add("usemap");
        tabList.add("srcdoc");
        tabList.add("header");
        tabList.add("footer");
        tabList.add("main");
        tabList.add("article");
        tabList.add("aside");
        tabList.add("section");
        tabList.add("details");
        tabList.add("dialog");
        tabList.add("figcaption");
        tabList.add("figure");
        tabList.add("mark");
        tabList.add("nav");
        tabList.add("menuitem");
        tabList.add("meter");
        tabList.add("progress");
        tabList.add("rp");
        tabList.add("rt");
        tabList.add("ruby");
        tabList.add("summary");
        tabList.add("bdi");
        tabList.add("time");
        tabList.add("wbr");
        return  tabList;
    }

    public static ArrayList<String> getTabsData(){
        tabData = new ArrayList<>();
        tabData.add("<html>\n   \n</html>");
        tabData.add("<head>\n   \n</head>");
        tabData.add("<title> </title>");
        tabData.add("<body>\n   \n</body>");
        tabData.add("<style>\n   \n</style>");
        tabData.add("<script type=\"\" >\n   \n<script/>");
        tabData.add("<base href=\"\" target=\"\" />");
        tabData.add("<meta charset=\"\" />");
        tabData.add("<link rel=\"\" href=\"\" />");
        tabData.add("<a href=\"\" > </a>");
        tabData.add("<image src=\"\" alt=\"\" height=\"\" width=\"\" />");
        tabData.add("<h1> </h1>");
        tabData.add("<h2> </h2>");
        tabData.add("<h3> </h3>");
        tabData.add("<h4> </h4>");
        tabData.add("<h5> </h5>");
        tabData.add("<h6> </h6>");
        tabData.add("<div>\n   \n</div>");
        tabData.add("<p>\n   \n</p>");
        tabData.add("<span>\n   \n</span>");
        tabData.add("<br />");
        tabData.add("<hr />");
        tabData.add("<ol>\n   \n</ol>");
        tabData.add("<ul>\n   \n</ul>");
        tabData.add("<li> </li>");
        tabData.add("<dl>\n   \n</dl>");
        tabData.add("<dt> </dt>");
        tabData.add("<dd> </dd>");
        tabData.add("<map>\n   \n </map>");
        tabData.add("<area />");
        tabData.add("<strong> </strong>");
        tabData.add("<b> </b>");
        tabData.add("<em> </em>");
        tabData.add("<i> </i>");
        tabData.add("<cite> </cite>");
        tabData.add("<pre> </pre>");
        tabData.add("<q> </q>");
        tabData.add("<abbr> </abbr>");
        tabData.add("<acronym> </acronym>");
        tabData.add("<address> </address>");
        tabData.add("<dfn> </dfn>");
        tabData.add("<code> </code>");
        tabData.add("<font> </font>");
        tabData.add("<sub> </sub>");
        tabData.add("<sup> </sup>");
        tabData.add("<del> </del>");
        tabData.add("<ins> </ins>");
        tabData.add("<blockquote> </blockquote>");
        tabData.add("<small> </small>");
        tabData.add("<bdo> </bdo>");
        tabData.add(" charset=\"\" ");
        tabData.add(" target=\"\" ");
        tabData.add(" rel=\"\" ");
        tabData.add(" href=\"\" ");
        tabData.add(" id=\"\" ");
        tabData.add(" src=\"\" ");
        tabData.add(" alt=\"\" ");
        tabData.add(" align=\"\" ");
        tabData.add(" border=\"\" ");
        tabData.add(" vspace=\"\" ");
        tabData.add(" hspace=\"\" ");
        tabData.add(" height=\"\" ");
        tabData.add(" width=\"\" ");
        tabData.add(" name=\"\" ");
        tabData.add(" type=\"\" ");
        tabData.add("<form>\n   \n</form>");
        tabData.add("<fieldset>\n   \n</fieldset>");
        tabData.add("<legend> </legend>");
        tabData.add("<input type=\"\" > </input>");
        tabData.add("<label> </label>");
        tabData.add(" action=\"\" ");
        tabData.add(" method=\"\" ");
        tabData.add(" enctype=\"\" ");
        tabData.add(" autocomplete ");
        tabData.add(" novalidate ");
        tabData.add(" accept-charsets ");
        tabData.add(" target ");
        tabData.add(" value=\"\" ");
        tabData.add(" size=\"\" ");
        tabData.add(" maxlength=\"\" ");
        tabData.add(" required ");
        tabData.add(" step=\"\" ");
        tabData.add(" placeholder=\"\" ");
        tabData.add(" pattern=\"\" ");
        tabData.add(" min=\"\" ");
        tabData.add(" max=\"\" ");
        tabData.add(" autofocus ");
        tabData.add(" disabled ");
        tabData.add("<textarea> </textarea>");
        tabData.add("<select>\n   \n</select>");
        tabData.add(" multiple ");
        tabData.add("<optgroup>\n   \n</optgroup>");
        tabData.add("<option> </option>");
        tabData.add(" selected ");
        tabData.add("<button> </button>");
        tabData.add("<table>\n   \n</table>");
        tabData.add("<caption> </caption>");
        tabData.add("<thead> </thead>");
        tabData.add("<tbody> </tbody>");
        tabData.add("<tfoot> </tfoot>");
        tabData.add("<tr>\n   \n</tr>");
        tabData.add("<th> </th>");
        tabData.add("<td> </td>");
        tabData.add("<colgroup>\n   \n</colgroup>");
        tabData.add("<col />");
        tabData.add("<object type=\"\" width=\"\" height=\"\" >\n   \n</object>");
        tabData.add("<iframe src=\"\" width=\"\" height=\"\" >\n   \n</iframe>");
        tabData.add("<param />");
        tabData.add("<embed src=\"\" width=\"\" height=\"\" >\n   \n</embed>");
        tabData.add(" usemap=\"\" ");
        tabData.add(" srcdoc=\"\" ");
        tabData.add("<header> </header>");
        tabData.add("<footer> </footer>");
        tabData.add("<main> </main>");
        tabData.add("<article> </article>");
        tabData.add("<aside> </aside>");
        tabData.add("<section> </section>");
        tabData.add("<details> </details>");
        tabData.add("<dialog> </dialog>");
        tabData.add("<figcaption> </figcaption>");
        tabData.add("<figure> </figure>");
        tabData.add("<mark> </mark>");
        tabData.add("<nav> </nav>");
        tabData.add("<menuitem> </menuitem>");
        tabData.add("<meter> </meter>");
        tabData.add("<progress> </progress>");
        tabData.add("<rp> </rp>");
        tabData.add("<rt> </rt>");
        tabData.add("<ruby> </ruby>");
        tabData.add("<summary> </summary>");
        tabData.add("<bdi> </bdi>");
        tabData.add("<time> </time>");
        tabData.add("<wbr >");
        return  tabData;
    }

}
